
using System;
using System.Collections.Generic;
using MiyakoCarryService.Client.Enums;

namespace MiyakoCarryService.Assistant.Utils
{
    public class Classification
    {
        public const string Terminology = """
            TERMINOLOGY — authoritative project terms. Use them exactly; never rename or paraphrase them:
            - Mcs (宫子护航店 / Miyako Carry Service): this mod.
            - 老板 / McsLeadPlayer: the human player who is speaking (the one commanding the squad).
            - 护航 / McsBotPlayer: the AI teammate(s) generated by Mcs; they are the targets of your commands.
            - 护航Boss: a boss-type 护航 (McsBotPlayer).
            - 店长: Tsukiyuki Miyako (月雪宫子), the trader of this mod.
            - 制作人 (Producer): the mod author.
            - 打手: sponsors; 护航 are randomly drawn from the 打手 list when an 订单 is placed.
            - 订单 / order: a carry-service order; 罚单 / ticket: a fine-relief ticket against the 涨价惩罚 (price-increase punishment).
            - 代号 (BrevityCode): the code name of each 护航 (e.g. Rabbit1). Always call it 代号; never translate it as 呼号 or 编号.
            Reply rule: use these exact terms when replying — Chinese terms when the player speaks Chinese, English terms otherwise.
            """;

        public static readonly Dictionary<string, HashSet<string>> CommandGlossary = new()
        {
            { ECommandType.FollowMe.ToString(),                    [ClientLocales.FOLLOWMECOMMAND_NAME] },
            { ECommandType.HoldPosition.ToString(),                [ClientLocales.HOLDPOSITIONCOMMAND_NAME] },
            { ECommandType.Regroup.ToString(),                     [ClientLocales.REGROUPCOMMAND_NAME] },
            { ECommandType.OnYourOwn.ToString(),                   [ClientLocales.ONYOUROWNCOMMAND_NAME] },
            { ECommandType.ChangeFormation.ToString(),             [ClientLocales.CHANGEFORMATIONCOMMAND_NAME] },
            { ECommandType.GoToExfil.ToString(),                   [ClientLocales.EXFILESCORTCOMMAND_NAME] },
            { ECommandType.ClearArea.ToString(),                   [ClientLocales.CLEARAREACOMMAND_NAME] },
            { ECommandType.OpenInventory.ToString(),               [ClientLocales.OPENINVENTORYCOMMAND_NAME] },
            { ECommandType.ExcludeOrTakeOver.ToString(),           [ClientLocales.EXCLUDEORTAKEOVERCOMMAND_NAME] },
            { ECommandType.ReportAboutEnemy.ToString(),            [ClientLocales.REPORTABOUTENEMYCOMMAND_NAME] },
            { ECommandType.ReportAboutSelf.ToString(),             [ClientLocales.REPORTABOUTSELFCOMMAND_NAME] },
            { ECommandType.EscortBtr.ToString(),                   [ClientLocales.BTRESCORTCOMMAND_NAME] },
            { ECommandType.GoToPoint.ToString(),                   [ClientLocales.GOTOPOINTCOMMAND_NAME] },
            { ECommandType.EscortWorld.ToString(),                 [ClientLocales.ESCORTCOMMAND_NAME] },
            { ECommandType.Teleport.ToString(),                    [ClientLocales.FORCETELEPORTCOMMAND_NAME] },
            { ECommandType.AimingBodyPart.ToString(),              [ClientLocales.CHANGEAIMINGBODYPARTTYPECOMMAND_NAME] },
            { ECommandType.QuestProxyAction.ToString(),            [ClientLocales.QUESTPROXYCOMMAND_NAME] },
            { ECommandType.LootProxyAction.ToString(),             [ClientLocales.LOOTPROXYCOMMAND_NAME] },
            { ECommandType.InteractionProxyAction.ToString(),      [ClientLocales.SWITCHPROXYCOMMAND_NAME, ClientLocales.DOORPROXYCOMMAND_NAME] },
            { ECommandType.StationaryWeaponProxyAction.ToString(), [ClientLocales.STATIONARYWEAPONPROXYCOMMAND_NAME] },
            { ECommandType.DropTargetLoot.ToString(),              [ClientLocales.DROPTARGETLOOTCOMMAND_NAME] },
        };

        public static readonly HashSet<string> UsableCommands =
        [
            ECommandType.FollowMe.ToString(),
            ECommandType.HoldPosition.ToString(),
            ECommandType.Regroup.ToString(),
            ECommandType.OnYourOwn.ToString(),
            ECommandType.ChangeFormation.ToString(),
            ECommandType.GoToExfil.ToString(),
            ECommandType.ClearArea.ToString(),
            ECommandType.OpenInventory.ToString(),
            ECommandType.ExcludeOrTakeOver.ToString(),
            ECommandType.ReportAboutEnemy.ToString(),
            ECommandType.ReportAboutSelf.ToString(),
            ECommandType.EscortBtr.ToString(),
            ECommandType.GoToPoint.ToString(),
            ECommandType.EscortWorld.ToString(),
            ECommandType.Teleport.ToString(),
            ECommandType.AimingBodyPart.ToString(),
            ECommandType.QuestProxyAction.ToString(),
            ECommandType.LootProxyAction.ToString(),
            ECommandType.InteractionProxyAction.ToString(),
            ECommandType.StationaryWeaponProxyAction.ToString(),
            ECommandType.DropTargetLoot.ToString(),
        ];

        public static readonly HashSet<string> AimingBodyParts = [.. Enum.GetNames(typeof(BodyPartType))];
    }
}