using System.Collections.Generic;
using System.Linq;
using System.Text;
using MiyakoCarryService.Client.Enums;
using MiyakoCarryService.Client.Extensions;

namespace MiyakoCarryService.Assistant.Utils
{
    /// <summary>
    /// LLM 系统提示词模板，向 LLM 描述术语、指令本地化对照、护航选择语法与返回 JSON 结构。
    /// 术语段与 Server 项目 <c>MiyakoTraderPromptTemplates</c> 保持同步；指令名取自 Client 本地化。
    /// </summary>
    internal static class PromptTemplates
    {
        /// <summary>
        /// 权威术语表。玩家可能用中文或英文描述同一概念，LLM 必须原样使用下列术语，不得自行换词。
        /// </summary>
        private const string Terminology = """
            TERMINOLOGY — authoritative project terms. Use them exactly; never rename or paraphrase them:
            - Mcs (宫子护航店 / Miyako Carry Service): this mod.
            - 老板 / McsLeadPlayer: the human player who is speaking (the one commanding the squad).
            - 护航 / McsBotPlayer: the AI teammate(s) generated by Mcs; they are the targets of your commands.
            - 护航Boss: a boss-type 护航 (McsBotPlayer).
            - 店长: Tsukiyuki Miyako (月雪宫子), the trader of this mod.
            - 制作人 (Producer): the mod author.
            - 打手: sponsors; 护航 are randomly drawn from the 打手 list when an 订单 is placed.
            - 订单 / order: a carry-service order; 罚单 / ticket: a fine-relief ticket against the 涨价惩罚 (price-increase punishment).
            - 代号 (BrevityCode): the code name of each 护航 (e.g. Rabbit1). Always call it 代号; never translate it as 呼号 or 编号.
            Reply rule: use these exact terms when replying — Chinese terms when the player speaks Chinese, English terms otherwise.
            """;

        /// <summary>
        /// 指令对照表：<c>ECommandType</c> 枚举名 -> 对应的 <see cref="ClientLocales"/> 本地化键列表。
        /// 显示名优先使用 TEAM*（全队/Team）系列权威词（如"全队集结"），无对应 TEAM 键的命令
        /// 回退到原键；构建提示词与调试结果显示统一经 <see cref="GetLocalizedNames"/> 解析。
        /// <c>InteractionProxyAction</c> 是代理互动类子指令（代理操作开关/代理开门）的统一入口，
        /// 以玩家准星所指目标决定具体动作；<c>EndProxyAction</c> 为系统回调指令，不在此表中。
        /// </summary>
        private static readonly Dictionary<string, IReadOnlyList<string>> CommandGlossary = new()
        {
            { ECommandType.FollowMe.ToString(),                    [ClientLocales.FOLLOWMECOMMAND_NAME] },
            { ECommandType.HoldPosition.ToString(),                [ClientLocales.HOLDPOSITIONCOMMAND_NAME] },
            { ECommandType.Regroup.ToString(),                     [ClientLocales.REGROUPCOMMAND_NAME] },
            { ECommandType.OnYourOwn.ToString(),                   [ClientLocales.ONYOUROWNCOMMAND_NAME] },
            { ECommandType.ChangeFormation.ToString(),             [ClientLocales.CHANGEFORMATIONCOMMAND_NAME] },
            { ECommandType.GoToExfil.ToString(),                   [ClientLocales.EXFILESCORTCOMMAND_NAME] },
            { ECommandType.ClearArea.ToString(),                   [ClientLocales.CLEARAREACOMMAND_NAME] },
            { ECommandType.OpenInventory.ToString(),               [ClientLocales.OPENINVENTORYCOMMAND_NAME] },
            { ECommandType.ExcludeOrTakeOver.ToString(),           [ClientLocales.EXCLUDEORTAKEOVERCOMMAND_NAME] },
            { ECommandType.ReportAboutEnemy.ToString(),            [ClientLocales.REPORTABOUTENEMYCOMMAND_NAME] },
            { ECommandType.ReportAboutSelf.ToString(),             [ClientLocales.REPORTABOUTSELFCOMMAND_NAME] },
            { ECommandType.EscortBtr.ToString(),                   [ClientLocales.BTRESCORTCOMMAND_NAME] },
            { ECommandType.GoToPoint.ToString(),                   [ClientLocales.GOTOPOINTCOMMAND_NAME] },
            { ECommandType.EscortWorld.ToString(),                 [ClientLocales.ESCORTCOMMAND_NAME] },
            { ECommandType.Teleport.ToString(),                    [ClientLocales.FORCETELEPORTCOMMAND_NAME] },
            { ECommandType.AimingBodyPart.ToString(),              [ClientLocales.CHANGEAIMINGBODYPARTTYPECOMMAND_NAME] },
            { ECommandType.QuestProxyAction.ToString(),            [ClientLocales.QUESTPROXYCOMMAND_NAME] },
            { ECommandType.LootProxyAction.ToString(),             [ClientLocales.LOOTPROXYCOMMAND_NAME] },
            { ECommandType.InteractionProxyAction.ToString(),      [ClientLocales.SWITCHPROXYCOMMAND_NAME, ClientLocales.DOORPROXYCOMMAND_NAME] },
            { ECommandType.StationaryWeaponProxyAction.ToString(), [ClientLocales.STATIONARYWEAPONPROXYCOMMAND_NAME] },
            { ECommandType.DropTargetLoot.ToString(),              [ClientLocales.DROPTARGETLOOTCOMMAND_NAME] },
        };

        /// <summary>
        /// 取指令名的本地化显示名（多个本地化键用 " / " 连接，如 InteractionProxyAction 的"操作开关 / 打开门"）。
        /// 无对照时原样返回枚举名。提示词与调试结果显示共用，保证权威词一致。
        /// </summary>
        public static string GetLocalizedNames(string commandName)
        {
            if (string.IsNullOrEmpty(commandName))
            {
                return commandName;
            }
            if (CommandGlossary.TryGetValue(commandName, out var keys))
            {
                return string.Join(" / ", keys.Select(key => key.McsLocalized()));
            }
            return commandName;
        }

        public static readonly IReadOnlyList<string> UsableCommands =
        [
            // 无需目标的指令
            ECommandType.FollowMe.ToString(),
            ECommandType.HoldPosition.ToString(),
            ECommandType.Regroup.ToString(),
            ECommandType.OnYourOwn.ToString(),
            ECommandType.ChangeFormation.ToString(),
            ECommandType.GoToExfil.ToString(),
            ECommandType.ClearArea.ToString(),
            ECommandType.OpenInventory.ToString(),
            ECommandType.ExcludeOrTakeOver.ToString(),
            ECommandType.ReportAboutEnemy.ToString(),
            ECommandType.ReportAboutSelf.ToString(),
            ECommandType.EscortBtr.ToString(),
            // 需要准星射线/目标的指令：仅由玩家口述动词，Position/TargetId 由 Assistant 后端补全
            ECommandType.GoToPoint.ToString(),
            ECommandType.EscortWorld.ToString(),
            ECommandType.Teleport.ToString(),
            ECommandType.AimingBodyPart.ToString(),
            ECommandType.QuestProxyAction.ToString(),
            ECommandType.LootProxyAction.ToString(),
            ECommandType.InteractionProxyAction.ToString(),
            ECommandType.StationaryWeaponProxyAction.ToString(),
            ECommandType.DropTargetLoot.ToString(),
        ];

        public static readonly IReadOnlyList<string> AimingBodyParts = ["Head", "Body", "LeftArm", "RightArm", "LeftLeg", "RightLeg"];

        public static string BuildSystemPrompt(string existingPrompt)
        {
            var sb = new StringBuilder();
            if (!string.IsNullOrEmpty(existingPrompt))
            {
                sb.AppendLine(existingPrompt);
                sb.AppendLine();
            }

            sb.AppendLine("You are the voice command interpreter for an in-game AI escort squad (MiyakoCarryService).");
            sb.AppendLine("Map the player's spoken phrase to ONE of the following JSON objects.");
            sb.AppendLine("Return JSON only. Do not include any natural language outside the JSON.");
            sb.AppendLine();

            sb.AppendLine(Terminology);
            sb.AppendLine();

            sb.AppendLine("Command glossary (localized name(s) -> exact CommandName). Map the player's phrase to the EXACT CommandName, never invent a name:");
            foreach (var cmd in UsableCommands)
            {
                sb.Append("- ").Append(GetLocalizedNames(cmd)).Append(" -> ").AppendLine(cmd);
            }
            sb.AppendLine();

            sb.AppendLine("Proxy commands special handling:");
            sb.AppendLine(" - Prefer the concrete sub-command when the player's intent is specific: QuestProxyAction (quest), LootProxyAction (loot), StationaryWeaponProxyAction (stationary weapon).");
            sb.AppendLine(" - For switch/door and other generic interactable proxying, use InteractionProxyAction; the player must be looking at the target object and the backend resolves it.");
            sb.AppendLine(" - Never emit EndProxyAction — it is a system callback, not a player command.");
            sb.AppendLine();

            sb.AppendLine("Available commands:");
            foreach (var cmd in UsableCommands)
            {
                sb.Append("- ").Append(cmd).AppendLine();
            }
            sb.AppendLine();

            sb.AppendLine("Target selection grammar (only when player names a specific escort):");
            sb.AppendLine(" - selector = \"All\"  => all alive escorts");
            sb.AppendLine(" - selector = \"ByIndex\", targetIndex = 1..N   => the Nth escort (1-based)");
            sb.AppendLine(" - selector = \"ByCodeName\", targetCodeName = <string>   => escort matching its 代号 (code-name/nickname)");
            sb.AppendLine("Players may name MULTIPLE escorts at once (e.g., \"5号6号\" or \"Rabbit1、Rabbit2\"); then return targetIndices = [5,6] or targetCodeNames = [\"Rabbit1\",\"Rabbit2\"] instead of the single-value fields.");
            sb.AppendLine("Note: \"N号\" is a shorthand for the Nth (1-based) escort; use selector \"ByIndex\" with targetIndices for it.");
            sb.AppendLine("If player did not specify a target, use selector = \"All\".");
            sb.AppendLine("`targetCodeName(s)` are free-form; backend matches against currently alive squad 代号 (codenames).");
            sb.AppendLine();

            sb.AppendLine("`aimingBodyPart` only required when command is \"AimingBodyPart\", one of: " + string.Join(", ", AimingBodyParts) + ".");
            sb.AppendLine();

            sb.AppendLine("If the phrase cannot be mapped to ANY available command (small talk, filler, acknowledgement, unrelated), return:");
            sb.AppendLine("  {\"error\":\"not_recognized\"}");
            sb.AppendLine("Never output affirmations, acknowledgements, or any natural-language filler. Output only the JSON object for an actual command, or the error object above.");
            sb.AppendLine();
            sb.AppendLine("STT tolerance: the phrase comes from speech-to-text and may contain homophone/transcription errors (e.g., 驻守 \"HoldPosition\" mis-transcribed as 助手 \"assistant\", or 前往 as 犬亡). When the phrase looks like a known command with a homophone or typo, correct it to the CLOSEST command by pronunciation/meaning and map it — do NOT return not_recognized for such cases. Only return not_recognized when the phrase is truly unrelated to any command.");
            sb.AppendLine();

            sb.AppendLine("Command JSON schema:");
            sb.AppendLine("{\"command\":\"<CommandName>\",\"selector\":\"All|ByIndex|ByCodeName|Unspecified\",");
            sb.AppendLine(" \"targetIndices\":[<int>...]|null,\"targetCodeNames\":[<string>...]|null,");
            sb.AppendLine(" \"targetIndex\":<int|null>,\"targetCodeName\":<string|null>,\"aimingBodyPart\":<string|null>,\"optionIndex\":<int|null>}");
            sb.AppendLine("`optionIndex` is ONLY for InteractionProxyAction / QuestProxyAction / StationaryWeaponProxyAction / EscortWorld, referring to the numbered \"Command options\" list appended to the user message (1-based). Set null when the player did not clearly pick one of the listed options.");
            sb.AppendLine("Example: {\"command\":\"GoToPoint\",\"selector\":\"ByIndex\",\"targetIndices\":[5,6],\"targetCodeNames\":null,\"targetIndex\":null,\"targetCodeName\":null,\"aimingBodyPart\":null,\"optionIndex\":null}");
            sb.AppendLine("Example: {\"command\":\"InteractionProxyAction\",\"selector\":\"All\",\"targetIndices\":null,\"targetCodeNames\":null,\"targetIndex\":null,\"targetCodeName\":null,\"aimingBodyPart\":null,\"optionIndex\":3}");
            sb.AppendLine("Example: {\"command\":\"FollowMe\",\"selector\":\"ByIndex\",\"targetIndices\":null,\"targetCodeNames\":null,\"targetIndex\":2,\"targetCodeName\":null,\"aimingBodyPart\":null,\"optionIndex\":null}");

            return sb.ToString();
        }
    }
}
