<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>disable</Nullable>
    <DevServerPath>D:\OtherGames\SPT4.1.X\SPT-4.1.X</DevServerPath>
    <DevGamePluginsMiyakoCarryServicePath>$(DevServerPath)\SPT_Runtime\user\mods\MiyakoCarryServiceServer</DevGamePluginsMiyakoCarryServicePath>
    <BuildMiyakoCarryServicePath>$(ProjectDir)..\Build\Plugin\SPT_Runtime\user\mods\MiyakoCarryServiceServer</BuildMiyakoCarryServicePath>  
    <OutputType>Library</OutputType>
    <AssemblyName>Himesamanoyume.MiyakoCarryServiceServer</AssemblyName>
    <AssemblyCompany>Himesamanoyume</AssemblyCompany>
    <AssemblyProduct>MiyakoCarryService</AssemblyProduct>  
    <AssemblyCopyright>Copyright © 姫様の夢 2025 - 2026</AssemblyCopyright> 
    <AssemblyTitle>MiyakoCarryServiceServer</AssemblyTitle>  
    <Version>1.1.2.5</Version>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <DisableBuildCompression>true</DisableBuildCompression>
    <Trademark>https://sp-mod.com/mod/2709/miyako-carry-service</Trademark>
    <RootNamespace>MiyakoCarryService.Server</RootNamespace>
    <NoWarn>CS0618;CS8632;CS9107</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <!-- <Content Include="wwwroot\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content> -->
    <!-- <Content Include="Web\**\*.razor" /> -->
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SPTushonka.Common" Version="4.1.2" />
    <PackageReference Include="SPTushonka.DI" Version="4.1.2" />
    <PackageReference Include="SPTushonka.Reflection" Version="4.1.2" />
    <PackageReference Include="SPTushonka.Server.Core" Version="4.1.2" />
    <PackageReference Include="SPTushonka.Server.Web" Version="4.1.2" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">  
    <Exec Command="mkdir &quot;$(DevGamePluginsMiyakoCarryServicePath)&quot;" Condition="!Exists('$(DevGamePluginsMiyakoCarryServicePath)')" />
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(DevGamePluginsMiyakoCarryServicePath)\$(TargetFileName)&quot;" />  
    <Exec Command="mkdir &quot;$(BuildMiyakoCarryServicePath)&quot;" Condition="!Exists('$(BuildMiyakoCarryServicePath)')" />
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(BuildMiyakoCarryServicePath)\$(TargetFileName)&quot;" />
    <Exec Command="if exist &quot;$(BuildMiyakoCarryServicePath)\Assets&quot; rd /s /q &quot;$(BuildMiyakoCarryServicePath)\Assets&quot;" />
    <!-- <Exec Command="if exist &quot;$(BuildMiyakoCarryServicePath)\wwwroot&quot; rd /s /q &quot;$(BuildMiyakoCarryServicePath)\wwwroot&quot;" /> -->
    <Exec Command="xcopy &quot;$(TargetDir)Assets\*.*&quot; &quot;$(BuildMiyakoCarryServicePath)\Assets\&quot; /E /I /Y" />
    <Exec Command="xcopy &quot;$(TargetDir)Assets\*.*&quot; &quot;$(DevGamePluginsMiyakoCarryServicePath)\Assets\&quot; /E /I /Y" />
    <!-- <Exec Command="xcopy &quot;$(TargetDir)wwwroot\*.*&quot; &quot;$(BuildMiyakoCarryServicePath)\wwwroot\&quot; /E /I /Y" />
    <Exec Command="xcopy &quot;$(TargetDir)wwwroot\*.*&quot; &quot;$(DevGamePluginsMiyakoCarryServicePath)\wwwroot\&quot; /E /I /Y" /> -->
  </Target> 
</Project>
